/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/loadtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Loadtest
         * @description Burst-submit synthetic jobs so the System panel shows the semaphore
         *     working the vendor cap live. Same insert-then-enqueue path as /transcribe;
         *     the high-water mark is reset so the burst is measured from zero.
         */
        post: operations["loadtest_ops_loadtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ops */
        get: operations["ops_ops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Transcription */
        post: operations["submit_transcription_transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transcript/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Transcripts */
        get: operations["search_transcripts_transcript_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transcript/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transcript */
        get: operations["get_transcript_transcript__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChunkInfo */
        ChunkInfo: {
            /** Ordinal */
            ordinal: number;
            /** Audiopath */
            audioPath: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
        };
        /** ChunkStats */
        ChunkStats: {
            /** Bystatus */
            byStatus: {
                [key: string]: number;
            };
            /** Totalretries */
            totalRetries: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LatencyStats */
        LatencyStats: {
            /** Completedjobs */
            completedJobs: number;
            /** P50Seconds */
            p50Seconds: number | null;
            /** P95Seconds */
            p95Seconds: number | null;
        };
        /** LoadTestRequest */
        LoadTestRequest: {
            /**
             * Jobs
             * @default 40
             */
            jobs: number;
            /**
             * Chunks
             * @default 8
             */
            chunks: number;
        };
        /** LoadTestResponse */
        LoadTestResponse: {
            /** Jobssubmitted */
            jobsSubmitted: number;
            /** Chunkssubmitted */
            chunksSubmitted: number;
        };
        /** OpsResponse */
        OpsResponse: {
            semaphore: components["schemas"]["SemaphoreStats"];
            queue: components["schemas"]["QueueStats"];
            /** Jobs */
            jobs: {
                [key: string]: number;
            };
            chunks: components["schemas"]["ChunkStats"];
            latency: components["schemas"]["LatencyStats"];
        };
        /** QueueStats */
        QueueStats: {
            /** Depth */
            depth: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["TranscriptResult"][];
            /** Nextcursor */
            nextCursor?: string | null;
        };
        /** SemaphoreStats */
        SemaphoreStats: {
            /** Held */
            held: number;
            /** Highwatermark */
            highWaterMark: number;
            /** Capacity */
            capacity: number;
        };
        /** TranscribeRequest */
        TranscribeRequest: {
            /** Audiochunkpaths */
            audioChunkPaths: string[];
            /** Userid */
            userId: string;
        };
        /** TranscribeResponse */
        TranscribeResponse: {
            /**
             * Jobid
             * Format: uuid
             */
            jobId: string;
        };
        /** TranscriptResult */
        TranscriptResult: {
            /**
             * Jobid
             * Format: uuid
             */
            jobId: string;
            /** Userid */
            userId: string;
            /** Transcripttext */
            transcriptText: string | null;
            /** Chunkstatuses */
            chunkStatuses: {
                [key: string]: string;
            };
            /** Chunks */
            chunks: components["schemas"]["ChunkInfo"][];
            /** Jobstatus */
            jobStatus: string;
            /** Completedtime */
            completedTime: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    loadtest_ops_loadtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ops_ops_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsResponse"];
                };
            };
        };
    };
    submit_transcription_transcribe_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranscribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscribeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_transcripts_transcript_search_get: {
        parameters: {
            query?: {
                jobStatus?: string | null;
                userId?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_transcript__job_id__get: {
        parameters: {
            query?: {
                view?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
